# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.11.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(860, 350)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.actionCompras = QAction(MainWindow)
        self.actionCompras.setObjectName(u"actionCompras")
        self.actionCompras.setEnabled(False)
        self.actionEntrada = QAction(MainWindow)
        self.actionEntrada.setObjectName(u"actionEntrada")
        self.actionEntrada.setEnabled(False)
        self.action_CadProdutos = QAction(MainWindow)
        self.action_CadProdutos.setObjectName(u"action_CadProdutos")
        self.actionSa_da = QAction(MainWindow)
        self.actionSa_da.setObjectName(u"actionSa_da")
        self.actionSa_da.setEnabled(False)
        self.actionAltera_o = QAction(MainWindow)
        self.actionAltera_o.setObjectName(u"actionAltera_o")
        self.actionAltera_o.setEnabled(False)
        self.actionBaixa = QAction(MainWindow)
        self.actionBaixa.setObjectName(u"actionBaixa")
        self.actionBaixa.setEnabled(False)
        self.actionAuditoria = QAction(MainWindow)
        self.actionAuditoria.setObjectName(u"actionAuditoria")
        self.actionAuditoria.setEnabled(False)
        self.actionFazer_Pedido = QAction(MainWindow)
        self.actionFazer_Pedido.setObjectName(u"actionFazer_Pedido")
        self.actionConsultar_pedidos = QAction(MainWindow)
        self.actionConsultar_pedidos.setObjectName(u"actionConsultar_pedidos")
        self.action_cad_user = QAction(MainWindow)
        self.action_cad_user.setObjectName(u"action_cad_user")
        self.action_exitSystem = QAction(MainWindow)
        self.action_exitSystem.setObjectName(u"action_exitSystem")
        self.actionCadastro_De_Funcionarios = QAction(MainWindow)
        self.actionCadastro_De_Funcionarios.setObjectName(u"actionCadastro_De_Funcionarios")
        self.actionEstoque = QAction(MainWindow)
        self.actionEstoque.setObjectName(u"actionEstoque")
        self.actionRecriaDatabase = QAction(MainWindow)
        self.actionRecriaDatabase.setObjectName(u"actionRecriaDatabase")
        self.actionBuscarAtualizacao = QAction(MainWindow)
        self.actionBuscarAtualizacao.setObjectName(u"actionBuscarAtualizacao")
        self.actionAtualizar = QAction(MainWindow)
        self.actionAtualizar.setObjectName(u"actionAtualizar")
        self.actionAtualizafuturas = QAction(MainWindow)
        self.actionAtualizafuturas.setObjectName(u"actionAtualizafuturas")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 860, 33))
        self.menuEstoque = QMenu(self.menubar)
        self.menuEstoque.setObjectName(u"menuEstoque")
        self.menuPedidos = QMenu(self.menuEstoque)
        self.menuPedidos.setObjectName(u"menuPedidos")
        self.menuPedidos.setEnabled(False)
        self.menuVendas = QMenu(self.menubar)
        self.menuVendas.setObjectName(u"menuVendas")
        self.menuVendas.setEnabled(True)
        self.menuFinanceiro = QMenu(self.menubar)
        self.menuFinanceiro.setObjectName(u"menuFinanceiro")
        self.menuFinanceiro.setEnabled(True)
        self.menuClientes = QMenu(self.menubar)
        self.menuClientes.setObjectName(u"menuClientes")
        self.menuClientes.setEnabled(True)
        self.menuRH = QMenu(self.menubar)
        self.menuRH.setObjectName(u"menuRH")
        self.menuRH.setEnabled(True)
        self.menuajuda = QMenu(self.menubar)
        self.menuajuda.setObjectName(u"menuajuda")
        self.menuajuda.setEnabled(True)
        self.menuAtualizacao = QMenu(self.menubar)
        self.menuAtualizacao.setObjectName(u"menuAtualizacao")
        self.menuAtualizacao.setEnabled(True)
        self.menuconfiguracao = QMenu(self.menubar)
        self.menuconfiguracao.setObjectName(u"menuconfiguracao")
        self.menuconfiguracao.setEnabled(True)
        self.menuDatabase = QMenu(self.menuconfiguracao)
        self.menuDatabase.setObjectName(u"menuDatabase")
        self.menuSistema = QMenu(self.menubar)
        self.menuSistema.setObjectName(u"menuSistema")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuSistema.menuAction())
        self.menubar.addAction(self.menuEstoque.menuAction())
        self.menubar.addAction(self.menuClientes.menuAction())
        self.menubar.addAction(self.menuVendas.menuAction())
        self.menubar.addAction(self.menuFinanceiro.menuAction())
        self.menubar.addAction(self.menuRH.menuAction())
        self.menubar.addAction(self.menuconfiguracao.menuAction())
        self.menubar.addAction(self.menuajuda.menuAction())
        self.menubar.addAction(self.menuAtualizacao.menuAction())
        self.menuEstoque.addAction(self.action_CadProdutos)
        self.menuEstoque.addAction(self.menuPedidos.menuAction())
        self.menuEstoque.addAction(self.actionCompras)
        self.menuEstoque.addAction(self.actionEntrada)
        self.menuEstoque.addAction(self.actionSa_da)
        self.menuEstoque.addAction(self.actionAltera_o)
        self.menuEstoque.addAction(self.actionBaixa)
        self.menuEstoque.addAction(self.actionAuditoria)
        self.menuPedidos.addAction(self.actionFazer_Pedido)
        self.menuPedidos.addAction(self.actionConsultar_pedidos)
        self.menuRH.addAction(self.actionCadastro_De_Funcionarios)
        self.menuAtualizacao.addAction(self.actionBuscarAtualizacao)
        self.menuAtualizacao.addAction(self.actionAtualizar)
        self.menuAtualizacao.addAction(self.actionAtualizafuturas)
        self.menuconfiguracao.addAction(self.actionEstoque)
        self.menuconfiguracao.addAction(self.menuDatabase.menuAction())
        self.menuDatabase.addAction(self.actionRecriaDatabase)
        self.menuSistema.addAction(self.action_cad_user)
        self.menuSistema.addAction(self.action_exitSystem)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionCompras.setText(QCoreApplication.translate("MainWindow", u"Compras", None))
        self.actionEntrada.setText(QCoreApplication.translate("MainWindow", u"Entrada", None))
        self.action_CadProdutos.setText(QCoreApplication.translate("MainWindow", u"Cadastro de Produtos", None))
        self.actionSa_da.setText(QCoreApplication.translate("MainWindow", u"Sa\u00edda", None))
        self.actionAltera_o.setText(QCoreApplication.translate("MainWindow", u"Altera\u00e7\u00e3o", None))
        self.actionBaixa.setText(QCoreApplication.translate("MainWindow", u"Baixa", None))
        self.actionAuditoria.setText(QCoreApplication.translate("MainWindow", u"Auditoria", None))
        self.actionFazer_Pedido.setText(QCoreApplication.translate("MainWindow", u"Fazer Pedido", None))
        self.actionConsultar_pedidos.setText(QCoreApplication.translate("MainWindow", u"Consultar pedidos", None))
        self.action_cad_user.setText(QCoreApplication.translate("MainWindow", u"Cadastrar Usu\u00e1rio", None))
        self.action_exitSystem.setText(QCoreApplication.translate("MainWindow", u"Sair do sistema", None))
        self.actionCadastro_De_Funcionarios.setText(QCoreApplication.translate("MainWindow", u"Cadastro De Funcionarios", None))
        self.actionEstoque.setText(QCoreApplication.translate("MainWindow", u"Estoque", None))
        self.actionRecriaDatabase.setText(QCoreApplication.translate("MainWindow", u"Recria Database", None))
        self.actionBuscarAtualizacao.setText(QCoreApplication.translate("MainWindow", u"Buscar Atualiza\u00e7\u00e3o", None))
        self.actionAtualizar.setText(QCoreApplication.translate("MainWindow", u"Atualizar", None))
        self.actionAtualizafuturas.setText(QCoreApplication.translate("MainWindow", u"Atualiza\u00e7\u00f5es futuras", None))
        self.menuEstoque.setTitle(QCoreApplication.translate("MainWindow", u"Estoque", None))
        self.menuPedidos.setTitle(QCoreApplication.translate("MainWindow", u"Pedidos", None))
        self.menuVendas.setTitle(QCoreApplication.translate("MainWindow", u"Vendas", None))
        self.menuFinanceiro.setTitle(QCoreApplication.translate("MainWindow", u"Financeiro", None))
        self.menuClientes.setTitle(QCoreApplication.translate("MainWindow", u"Clientes", None))
        self.menuRH.setTitle(QCoreApplication.translate("MainWindow", u"RH", None))
        self.menuajuda.setTitle(QCoreApplication.translate("MainWindow", u"Ajuda", None))
        self.menuAtualizacao.setTitle(QCoreApplication.translate("MainWindow", u"Atualiza\u00e7\u00e3o", None))
        self.menuconfiguracao.setTitle(QCoreApplication.translate("MainWindow", u"Configura\u00e7\u00e3o", None))
        self.menuDatabase.setTitle(QCoreApplication.translate("MainWindow", u"Database", None))
        self.menuSistema.setTitle(QCoreApplication.translate("MainWindow", u"Sistema", None))
    # retranslateUi

