
/* CRIA BANCO DE DADOS */

CREATE DATABASE DBSISTEMA;

USE DBSISTEMA;


CREATE TABLE USER(
  IDUSER INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  USER VARCHAR(20) NOT NULL,
  PASSWORD VARCHAR(20) NOT NULL,
  USERACCESS ENUM('ADMIN', 'USER') NOT NULL
);

CREATE TABLE PRODUTOS(
  IDPRODUTOS INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  NOMEPRODUTO VARCHAR(100) NOT NULL,
  NOMECOMERCIAL VARCHAR(100),
  MARCA VARCHAR(100) NOT NULL,
  FORNECEDOR VARCHAR(100),
  FABRICANTE VARCHAR(100),
  CODSKU VARCHAR(100),
  CODBARRAS VARCHAR(100),
  CODNCM VARCHAR(100),
  CODCEST VARCHAR(100)
);

 CREATE TABLE FABRICANTE(
  IDFABRICANTE INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  FABRICANTE VARCHAR(30),
  CNPJ VARCHAR(50),
  TELEFONE VARCHAR(13)
 );

 CREATE TABLE FORNECEDOR(
  IDFORNECEDOR INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  FORNECEDOR VARCHAR(30),
  CNPJ VARCHAR(50),
  TELEFONE VARCHAR(13)
 );

 CREATE TABLE MARCA(
  IDMARCA INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  MARCA VARCHAR(30),
  CNPJ VARCHAR(50),
  TELEFONE VARCHAR(13)
 );


/* CONSTRAINT */



/* PROCEDURES */
