
/* CRIA BANCO DE DADOS */

CREATE DATABASE DBSISTEMA;

USE DBSISTEMA;


CREATE TABLE USER(
  IDUSER INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  USER VARCHAR(20) NOT NULL,
  PASSWORD VARCHAR(20) NOT NULL,
  USERACCESS ENUM('ADMIN', 'USER') NOT NULL
);



CREATE TABLE PRODUTOS(
  IDPRODUTOS INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  NOMEPRODUTO VARCHAR(100) NOT NULL,
  NOMECOMERCIAL VARCHAR(100),
  MARCA VARCHAR(100) NOT NULL,
  FORNECEDOR VARCHAR(100),
  CODSKU VARCHAR(100),
  CODBARRAS VARCHAR(100)
);


/* CONSTRAINT */



/* PROCEDURES */
