

/* CRIA BANCO DE DADOS */
CREATE DATABASE DBSISTEMA;

/* SELECIONA O BANCO DE DADOS */
USE DBSISTEMA;

/* CRIA DE TABELA USER */
CREATE TABLE USER(
  IDUSER INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  USER VARCHAR(20) NOT NULL,
  PASSWORD VARCHAR(20) NOT NULL,
  USERACCESS ENUM('ADMIN', 'USER', 'TESTE') NOT NULL,
  UNIQUE (USER)
);

/* CRIA DE TABELA PRODUTOS */
CREATE TABLE PRODUTOS(
  IDPRODUTOS INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  NOMEPRODUTO VARCHAR(100) NOT NULL,
  NOMECOMERCIAL VARCHAR(100),
  MARCA VARCHAR(100) NOT NULL,
  FORNECEDOR VARCHAR(100),
  FABRICANTE VARCHAR(100),
  CODSKU VARCHAR(100),
  CODBARRAS VARCHAR(100),
  CODNCM VARCHAR(100),
  CODCEST VARCHAR(100)
);

/* CRIA DE TABELA FABRICANTE */
 CREATE TABLE FABRICANTE(
  IDFABRICANTE INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  FABRICANTE VARCHAR(30),
  CNPJ VARCHAR(50),
  EMAIL VARCHAR(50),
  TELEFONE VARCHAR(20),
  TELEFONE2 VARCHAR(20),
  WEBSITE VARCHAR(50),
  RUA VARCHAR(50),
  NUMERO VARCHAR(6),
  ESTADO VARCHAR(12),
  CEP VARCHAR(9),
  BAIRRO VARCHAR(13),
  FRETE BOOLEAN,
  FORNECEDOR BOOLEAN
 );

/* CRIA DE TABELA FORNECEDOR */
 CREATE TABLE FORNECEDOR(
  IDFORNECEDOR INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  FORNECEDOR VARCHAR(30),
  CNPJ VARCHAR(50),
  EMAIL VARCHAR(50),
  TELEFONE VARCHAR(20),
  TELEFONE2 VARCHAR(20),
  WEBSITE VARCHAR(50),
  RUA VARCHAR(50),
  NUMERO VARCHAR(6),
  ESTADO VARCHAR(20),
  CEP VARCHAR(9),
  BAIRRO VARCHAR(13),
  FRETE BOOLEAN
 );

/* CRIA DE TABELA MARCA */
 CREATE TABLE MARCA(
  IDMARCA INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  MARCA VARCHAR(30),
  SITE VARCHAR(50)
 );

 /* CRIA TABELA FOTO */
 CREATE TABLE FOTO(
  IDFOTO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  FOTO LONGBLOB,
  ID_PRODUTOS INT
  );



/* CONSTRAINT */



/* PROCEDURES */
